services:
  - type: web
    name: wanderlust
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true